# Blog
keywords: Django, Python, Swift, iso
author: 이정민, dreamhnt89@gmail.com
description: 기록 보관소
avatar: /images/profile.jpg

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: 
facebook: 

# Comment
disqus: miniring
